### ISSUE TITLE
Google news stuck days ago

### ISSUE THREAD

**Issue by Massi-X** [android-police/androidpolice-public#111]
#### Expected behavior
Google news updates your articles just fine.

#### Actual behavior
Your feed is stuck on 5 days ago and I also see some strange sections (test 1, 2, 3) at the top.

#### Steps to reproduce the problem
Open google news, go to Android Police section. See good old news.

**Comment by Massi-X** [comment]
I see it is actually fixed so I close this! Delete test sections when you have time

**Comment by archon810** [comment]
Hooray!

Still not sure what caused it to stop refreshing, but I'm not holding my breath for them telling us.

**Comment by archon810** [comment]
Got this.

Hello Artem, 

Thanks for sharing the update.

We apologize for inconvenience caused to you. There was some temporary technical glitch due to which Google News Producer was unable to fetch the content from the feeds. Now the issue has been resolved, so the Producer should continue to fetch the content form your feeds. We would suggest you to monitor your edition for next few days and if still faces any significant delay in content update then please write back to us, we will investigate the issue in more depth.

Please feel free to contact us for any queries in future and we'll be happy to help you.

**Comment by Massi-X** [comment]
Great! Hope it'll works forever now!
